require('./bootstrap');
require('alpinejs');
require('moment')
require('owl.carousel')
require('jquery-bar-rating')
require('headroom')
require('jquery.scrollto')
require('bootstrap-notify')
require('./dore.scripts.landingpage')
require('./scripts.single.theme')
require('./custom')
